# Nom du workflow
name: Deploy Frontend to GitHub Pages

# Déclencheurs
on:
  push:
    branches:
      - main
    paths:
      - 'client/**' # Only run if client files change
  workflow_dispatch:

# Permissions
permissions:
  contents: read
  pages: write
  id-token: write

# Concurrency
concurrency:
  group: "pages"
  cancel-in-progress: true

# Jobs
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurer Pages (PAS BESOIN DE NODE ICI)
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3. Copier les fichiers du dossier 'client' (PAS DE BUILD NPM)
      - name: Prepare artifact directory
        run: |
          mkdir _site
          cp -a client/. _site/

      # 4. Charger l'artefact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      # 5. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4